FROM python:3.6
LABEL maintainer="Thomas Legrand"
WORKDIR /app
# Install dependencies
COPY requirements.txt /app
RUN pip install -r requirements.txt
# Copy source code
COPY Inference.py /app
ENTRYPOINT ["python", "Inference.py"]